// -----------------------------------------------------------------------
// ConsoleEx - A simple console window system for .NET Core
//
// Author: Nikolaos Protopapas
// Email: nikolaos.protopapas@gmail.com
// License: MIT
// -----------------------------------------------------------------------

using System.Collections.Generic;
using System.Reflection;
using SharpConsoleUI;
using SharpConsoleUI.Themes;
using Xunit;

namespace SharpConsoleUI.Tests.Themes;

/// <summary>
/// Backbone backward-compat test: ModernGray and Classic must stay byte-for-byte identical through the
/// theme-hierarchy refactor. Each member's value captured BEFORE the refactor is the golden reference.
/// When new ITheme members are added later, their pinned ModernGray/Classic values are appended here.
/// </summary>
public class BuiltInThemeGoldenTests
{
	private static readonly Dictionary<string, string> Golden = new()
	{
		{ "ModernGray.ActiveBorderForegroundColor", "Color(0, 255, 255)" },
		{ "ModernGray.ActiveTitleForegroundColor", "Color(0, 255, 255)" },
		{ "ModernGray.BarGraphBackgroundColor", "" },
		{ "ModernGray.BottomBarBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.BottomBarForegroundColor", "Color(238, 238, 238)" },
		{ "ModernGray.ButtonBackgroundColor", "Color(48, 48, 48)" },
		{ "ModernGray.ButtonDisabledBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.ButtonDisabledForegroundColor", "Color(128, 128, 128)" },
		{ "ModernGray.ButtonFocusedBackgroundColor", "Color(68, 68, 68)" },
		{ "ModernGray.ButtonFocusedForegroundColor", "Color(0, 255, 255)" },
		{ "ModernGray.ButtonForegroundColor", "Color(238, 238, 238)" },
		{ "ModernGray.ButtonSelectedBackgroundColor", "Color(58, 58, 58)" },
		{ "ModernGray.ButtonSelectedForegroundColor", "Color(255, 255, 255)" },
		{ "ModernGray.CheckboxBackgroundColor", "" },
		{ "ModernGray.CheckboxDisabledBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.CheckboxFocusedBackgroundColor", "Color(48, 48, 48)" },
		{ "ModernGray.CollapsibleHeaderFocusedBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.CollapsibleHeaderFocusedForegroundColor", "Color(0, 255, 255)" },
		{ "ModernGray.DatePickerBackgroundColor", "" },
		{ "ModernGray.DatePickerCalendarHeaderColor", "Color(0, 255, 255)" },
		{ "ModernGray.DatePickerCalendarSelectedColor", "Color(88, 88, 88)" },
		{ "ModernGray.DatePickerCalendarTodayColor", "Color(0, 255, 255)" },
		{ "ModernGray.DatePickerDisabledForegroundColor", "Color(128, 128, 128)" },
		{ "ModernGray.DatePickerFocusedBackgroundColor", "Color(68, 68, 68)" },
		{ "ModernGray.DatePickerFocusedForegroundColor", "Color(0, 255, 255)" },
		{ "ModernGray.DatePickerForegroundColor", "" },
		{ "ModernGray.DatePickerSegmentBackgroundColor", "Color(88, 88, 88)" },
		{ "ModernGray.DatePickerSegmentForegroundColor", "Color(255, 255, 255)" },
		{ "ModernGray.Description", "Professional dark theme with grayscale foundation and cyan accents, inspired by modern developer tools" },
		{ "ModernGray.DesktopBackgroundChar", " " },
		{ "ModernGray.DesktopBackgroundColor", "Color(28, 28, 28)" },
		{ "ModernGray.DesktopBackgroundGradient", "" },
		{ "ModernGray.DesktopForegroundColor", "Color(128, 128, 128)" },
		{ "ModernGray.DropdownBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.DropdownForegroundColor", "Color(238, 238, 238)" },
		{ "ModernGray.DropdownHighlightBackgroundColor", "Color(88, 88, 88)" },
		{ "ModernGray.DropdownHighlightForegroundColor", "Color(255, 255, 255)" },
		{ "ModernGray.InactiveBorderForegroundColor", "Color(128, 128, 128)" },
		{ "ModernGray.InactiveTitleForegroundColor", "Color(178, 178, 178)" },
		{ "ModernGray.LineGraphBackgroundColor", "" },
		{ "ModernGray.ListBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.ListHoverBackgroundColor", "Color(68, 68, 68)" },
		{ "ModernGray.ListHoverForegroundColor", "Color(238, 238, 238)" },
		{ "ModernGray.ListUnfocusedHighlightBackgroundColor", "Color(88, 88, 88)" },
		{ "ModernGray.ListUnfocusedHighlightForegroundColor", "Color(255, 255, 255)" },
		{ "ModernGray.MenuBarBackgroundColor", "" },
		{ "ModernGray.MenuBarForegroundColor", "" },
		{ "ModernGray.MenuBarHighlightBackgroundColor", "Color(68, 68, 68)" },
		{ "ModernGray.MenuBarHighlightForegroundColor", "Color(0, 255, 255)" },
		{ "ModernGray.MenuDropdownBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.MenuDropdownForegroundColor", "Color(238, 238, 238)" },
		{ "ModernGray.MenuDropdownHighlightBackgroundColor", "Color(88, 88, 88)" },
		{ "ModernGray.MenuDropdownHighlightForegroundColor", "Color(255, 255, 255)" },
		{ "ModernGray.ModalBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.ModalBorderForegroundColor", "Color(0, 255, 255)" },
		{ "ModernGray.ModalFlashColor", "Color(88, 88, 88)" },
		{ "ModernGray.ModalTitleForegroundColor", "Color(0, 255, 255)" },
		{ "ModernGray.Mode", "Dark" },
		{ "ModernGray.Name", "ModernGray" },
		{ "ModernGray.NotificationDangerWindowBackgroundColor", "Color(128, 0, 0)" },
		{ "ModernGray.NotificationInfoWindowBackgroundColor", "Color(95, 135, 175)" },
		{ "ModernGray.NotificationSuccessWindowBackgroundColor", "Color(0, 128, 0)" },
		{ "ModernGray.NotificationWarningWindowBackgroundColor", "Color(215, 135, 0)" },
		{ "ModernGray.NotificationWindowBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.ProgressBarFilledColor", "Color(0, 255, 255)" },
		{ "ModernGray.ProgressBarPercentageColor", "Color(238, 238, 238)" },
		{ "ModernGray.ProgressBarUnfilledColor", "Color(58, 58, 58)" },
		{ "ModernGray.PromptInputBackgroundColor", "Color(48, 48, 48)" },
		{ "ModernGray.PromptInputFocusedBackgroundColor", "Color(68, 68, 68)" },
		{ "ModernGray.PromptInputFocusedForegroundColor", "Color(255, 255, 255)" },
		{ "ModernGray.PromptInputForegroundColor", "Color(238, 238, 238)" },
		{ "ModernGray.ScrollbarThumbColor", "Color(0, 255, 255)" },
		{ "ModernGray.ScrollbarThumbUnfocusedColor", "Color(128, 128, 128)" },
		{ "ModernGray.ScrollbarTrackColor", "Color(58, 58, 58)" },
		{ "ModernGray.ScrollbarTrackUnfocusedColor", "Color(58, 58, 58)" },
		{ "ModernGray.SeparatorForegroundColor", "Color(58, 58, 58)" },
		{ "ModernGray.ShowModalShadow", "True" },
		{ "ModernGray.SliderFilledTrackColor", "Color(0, 255, 255)" },
		{ "ModernGray.SliderFocusedThumbColor", "Color(255, 255, 0)" },
		{ "ModernGray.SliderThumbColor", "Color(238, 238, 238)" },
		{ "ModernGray.SliderTrackColor", "Color(58, 58, 58)" },
		{ "ModernGray.SparklineBackgroundColor", "" },
		{ "ModernGray.StartMenuHeaderBackgroundColor", "" },
		{ "ModernGray.StartMenuHeaderForegroundColor", "" },
		{ "ModernGray.StartMenuInfoStripForegroundColor", "Color(128, 128, 128)" },
		{ "ModernGray.StartMenuSectionHeaderBackgroundColor", "Color(48, 48, 48)" },
		{ "ModernGray.StatusBarBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.StatusBarForegroundColor", "Color(178, 178, 178)" },
		{ "ModernGray.StatusBarShortcutForegroundColor", "Color(0, 255, 255)" },
		{ "ModernGray.TabContentBackgroundColor", "" },
		{ "ModernGray.TabContentBorderColor", "Color(0, 255, 255)" },
		{ "ModernGray.TabHeaderActiveBackgroundColor", "Color(68, 68, 68)" },
		{ "ModernGray.TabHeaderActiveFocusedBackgroundColor", "Color(0, 255, 255)" },
		{ "ModernGray.TabHeaderActiveFocusedForegroundColor", "Color(0, 0, 0)" },
		{ "ModernGray.TabHeaderActiveForegroundColor", "Color(0, 255, 255)" },
		{ "ModernGray.TabHeaderBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.TabHeaderDisabledBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.TabHeaderDisabledForegroundColor", "Color(88, 88, 88)" },
		{ "ModernGray.TabHeaderFocusedBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.TabHeaderFocusedForegroundColor", "Color(218, 218, 218)" },
		{ "ModernGray.TabHeaderForegroundColor", "Color(178, 178, 178)" },
		{ "ModernGray.TableBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.TableBorderColor", "Color(0, 255, 255)" },
		{ "ModernGray.TableForegroundColor", "Color(238, 238, 238)" },
		{ "ModernGray.TableHeaderBackgroundColor", "Color(48, 48, 48)" },
		{ "ModernGray.TableHeaderForegroundColor", "Color(0, 255, 255)" },
		{ "ModernGray.TableHoverBackgroundColor", "Color(68, 68, 68)" },
		{ "ModernGray.TableHoverForegroundColor", "Color(238, 238, 238)" },
		{ "ModernGray.TableScrollbarThumbColor", "Color(0, 255, 255)" },
		{ "ModernGray.TableScrollbarTrackColor", "Color(58, 58, 58)" },
		{ "ModernGray.TableSelectionBackgroundColor", "Color(88, 88, 88)" },
		{ "ModernGray.TableSelectionForegroundColor", "Color(255, 255, 255)" },
		{ "ModernGray.TableUnfocusedSelectionBackgroundColor", "Color(58, 58, 58)" },
		{ "ModernGray.TableUnfocusedSelectionForegroundColor", "Color(178, 178, 178)" },
		{ "ModernGray.TextEditFocusedNotEditing", "Color(58, 58, 58)" },
		{ "ModernGray.TimePickerBackgroundColor", "" },
		{ "ModernGray.TimePickerDisabledForegroundColor", "Color(128, 128, 128)" },
		{ "ModernGray.TimePickerFocusedBackgroundColor", "Color(68, 68, 68)" },
		{ "ModernGray.TimePickerFocusedForegroundColor", "Color(0, 255, 255)" },
		{ "ModernGray.TimePickerForegroundColor", "" },
		{ "ModernGray.TimePickerSegmentBackgroundColor", "Color(88, 88, 88)" },
		{ "ModernGray.TimePickerSegmentForegroundColor", "Color(255, 255, 255)" },
		{ "ModernGray.ToolbarBackgroundColor", "" },
		{ "ModernGray.ToolbarForegroundColor", "" },
		{ "ModernGray.TopBarBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.TopBarForegroundColor", "Color(238, 238, 238)" },
		{ "ModernGray.TreeBackgroundColor", "" },
		{ "ModernGray.TreeSelectionBackgroundColor", "Color(58, 58, 58)" },
		{ "ModernGray.TreeUnfocusedSelectionBackgroundColor", "Color(48, 48, 48)" },
		{ "ModernGray.UseDoubleLineBorderForModal", "True" },
		{ "ModernGray.WindowBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.WindowForegroundColor", "Color(238, 238, 238)" },
		{ "ModernGray.DropdownFocusedForegroundColor", "Color(0, 255, 255)" },
		{ "ModernGray.DropdownFocusedBackgroundColor", "Color(68, 68, 68)" },
		{ "ModernGray.DropdownDisabledForegroundColor", "Color(128, 128, 128)" },
		{ "ModernGray.DropdownDisabledBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.ListForegroundColor", "Color(238, 238, 238)" },
		{ "ModernGray.ListFocusedForegroundColor", "Color(0, 255, 255)" },
		{ "ModernGray.ListSelectedForegroundColor", "Color(255, 255, 255)" },
		{ "ModernGray.ListSelectedBackgroundColor", "Color(58, 58, 58)" },
		{ "ModernGray.ListDisabledForegroundColor", "Color(128, 128, 128)" },
		{ "ModernGray.ListDisabledBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.CheckboxForegroundColor", "Color(238, 238, 238)" },
		{ "ModernGray.CheckboxFocusedForegroundColor", "Color(0, 255, 255)" },
		{ "ModernGray.CheckboxDisabledForegroundColor", "Color(128, 128, 128)" },
		{ "ModernGray.CheckboxCheckmarkColor", "Color(0, 255, 255)" },
		{ "ModernGray.DatePickerDisabledBackgroundColor", "Color(38, 38, 38)" },
		{ "ModernGray.HtmlForegroundColor", "Color(238, 238, 238)" },
		{ "Classic.ActiveBorderForegroundColor", "Color(0, 128, 0)" },
		{ "Classic.ActiveTitleForegroundColor", "Color(0, 128, 0)" },
		{ "Classic.BarGraphBackgroundColor", "" },
		{ "Classic.BottomBarBackgroundColor", "Color(0, 0, 255)" },
		{ "Classic.BottomBarForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.ButtonBackgroundColor", "Color(98, 98, 98)" },
		{ "Classic.ButtonDisabledBackgroundColor", "Color(128, 128, 128)" },
		{ "Classic.ButtonDisabledForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.ButtonFocusedBackgroundColor", "Color(0, 0, 255)" },
		{ "Classic.ButtonFocusedForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.ButtonForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.ButtonSelectedBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.ButtonSelectedForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.CheckboxBackgroundColor", "" },
		{ "Classic.CheckboxDisabledBackgroundColor", "Color(128, 128, 128)" },
		{ "Classic.CheckboxFocusedBackgroundColor", "Color(0, 0, 255)" },
		{ "Classic.CollapsibleHeaderFocusedBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.CollapsibleHeaderFocusedForegroundColor", "Color(0, 128, 0)" },
		{ "Classic.DatePickerBackgroundColor", "" },
		{ "Classic.DatePickerCalendarHeaderColor", "Color(255, 255, 0)" },
		{ "Classic.DatePickerCalendarSelectedColor", "Color(0, 0, 255)" },
		{ "Classic.DatePickerCalendarTodayColor", "Color(0, 255, 255)" },
		{ "Classic.DatePickerDisabledForegroundColor", "Color(128, 128, 128)" },
		{ "Classic.DatePickerFocusedBackgroundColor", "Color(0, 0, 255)" },
		{ "Classic.DatePickerFocusedForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.DatePickerForegroundColor", "" },
		{ "Classic.DatePickerSegmentBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.DatePickerSegmentForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.Description", "Classic Windows-style theme with bright blue and green accents" },
		{ "Classic.DesktopBackgroundChar", " " },
		{ "Classic.DesktopBackgroundColor", "Color(38, 38, 38)" },
		{ "Classic.DesktopBackgroundGradient", "" },
		{ "Classic.DesktopForegroundColor", "Color(58, 58, 58)" },
		{ "Classic.DropdownBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.DropdownForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.DropdownHighlightBackgroundColor", "Color(0, 0, 255)" },
		{ "Classic.DropdownHighlightForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.InactiveBorderForegroundColor", "Color(128, 128, 128)" },
		{ "Classic.InactiveTitleForegroundColor", "Color(128, 128, 128)" },
		{ "Classic.LineGraphBackgroundColor", "" },
		{ "Classic.ListBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.ListHoverBackgroundColor", "" },
		{ "Classic.ListHoverForegroundColor", "" },
		{ "Classic.ListUnfocusedHighlightBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.ListUnfocusedHighlightForegroundColor", "Color(192, 192, 192)" },
		{ "Classic.MenuBarBackgroundColor", "" },
		{ "Classic.MenuBarForegroundColor", "" },
		{ "Classic.MenuBarHighlightBackgroundColor", "Color(0, 0, 255)" },
		{ "Classic.MenuBarHighlightForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.MenuDropdownBackgroundColor", "Color(255, 255, 255)" },
		{ "Classic.MenuDropdownForegroundColor", "Color(0, 0, 0)" },
		{ "Classic.MenuDropdownHighlightBackgroundColor", "Color(0, 0, 255)" },
		{ "Classic.MenuDropdownHighlightForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.ModalBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.ModalBorderForegroundColor", "Color(255, 255, 0)" },
		{ "Classic.ModalFlashColor", "Color(255, 255, 0)" },
		{ "Classic.ModalTitleForegroundColor", "Color(255, 255, 0)" },
		{ "Classic.Mode", "Light" },
		{ "Classic.Name", "Classic" },
		{ "Classic.NotificationDangerWindowBackgroundColor", "Color(128, 0, 0)" },
		{ "Classic.NotificationInfoWindowBackgroundColor", "Color(95, 135, 175)" },
		{ "Classic.NotificationSuccessWindowBackgroundColor", "Color(0, 128, 0)" },
		{ "Classic.NotificationWarningWindowBackgroundColor", "Color(215, 135, 0)" },
		{ "Classic.NotificationWindowBackgroundColor", "Color(128, 128, 128)" },
		{ "Classic.ProgressBarFilledColor", "Color(0, 255, 255)" },
		{ "Classic.ProgressBarPercentageColor", "Color(255, 255, 255)" },
		{ "Classic.ProgressBarUnfilledColor", "Color(88, 88, 88)" },
		{ "Classic.PromptInputBackgroundColor", "Color(58, 58, 58)" },
		{ "Classic.PromptInputFocusedBackgroundColor", "Color(118, 118, 118)" },
		{ "Classic.PromptInputFocusedForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.PromptInputForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.ScrollbarThumbColor", "Color(0, 128, 0)" },
		{ "Classic.ScrollbarThumbUnfocusedColor", "Color(128, 128, 128)" },
		{ "Classic.ScrollbarTrackColor", "Color(58, 58, 58)" },
		{ "Classic.ScrollbarTrackUnfocusedColor", "Color(58, 58, 58)" },
		{ "Classic.SeparatorForegroundColor", "Color(128, 128, 128)" },
		{ "Classic.ShowModalShadow", "True" },
		{ "Classic.SliderFilledTrackColor", "Color(0, 255, 255)" },
		{ "Classic.SliderFocusedThumbColor", "Color(255, 255, 0)" },
		{ "Classic.SliderThumbColor", "Color(255, 255, 255)" },
		{ "Classic.SliderTrackColor", "Color(88, 88, 88)" },
		{ "Classic.SparklineBackgroundColor", "" },
		{ "Classic.StartMenuHeaderBackgroundColor", "" },
		{ "Classic.StartMenuHeaderForegroundColor", "" },
		{ "Classic.StartMenuInfoStripForegroundColor", "Color(128, 128, 128)" },
		{ "Classic.StartMenuSectionHeaderBackgroundColor", "" },
		{ "Classic.StatusBarBackgroundColor", "" },
		{ "Classic.StatusBarForegroundColor", "" },
		{ "Classic.StatusBarShortcutForegroundColor", "" },
		{ "Classic.TabContentBackgroundColor", "" },
		{ "Classic.TabContentBorderColor", "Color(0, 128, 0)" },
		{ "Classic.TabHeaderActiveBackgroundColor", "Color(0, 0, 255)" },
		{ "Classic.TabHeaderActiveFocusedBackgroundColor", "Color(0, 255, 255)" },
		{ "Classic.TabHeaderActiveFocusedForegroundColor", "Color(0, 0, 0)" },
		{ "Classic.TabHeaderActiveForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.TabHeaderBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.TabHeaderDisabledBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.TabHeaderDisabledForegroundColor", "Color(128, 128, 128)" },
		{ "Classic.TabHeaderFocusedBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.TabHeaderFocusedForegroundColor", "Color(192, 192, 192)" },
		{ "Classic.TabHeaderForegroundColor", "Color(192, 192, 192)" },
		{ "Classic.TableBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.TableBorderColor", "Color(0, 128, 0)" },
		{ "Classic.TableForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.TableHeaderBackgroundColor", "Color(0, 0, 255)" },
		{ "Classic.TableHeaderForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.TableHoverBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.TableHoverForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.TableScrollbarThumbColor", "Color(0, 128, 0)" },
		{ "Classic.TableScrollbarTrackColor", "Color(128, 128, 128)" },
		{ "Classic.TableSelectionBackgroundColor", "Color(0, 0, 255)" },
		{ "Classic.TableSelectionForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.TableUnfocusedSelectionBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.TableUnfocusedSelectionForegroundColor", "Color(192, 192, 192)" },
		{ "Classic.TextEditFocusedNotEditing", "Color(88, 88, 88)" },
		{ "Classic.TimePickerBackgroundColor", "" },
		{ "Classic.TimePickerDisabledForegroundColor", "Color(128, 128, 128)" },
		{ "Classic.TimePickerFocusedBackgroundColor", "Color(0, 0, 255)" },
		{ "Classic.TimePickerFocusedForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.TimePickerForegroundColor", "" },
		{ "Classic.TimePickerSegmentBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.TimePickerSegmentForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.ToolbarBackgroundColor", "" },
		{ "Classic.ToolbarForegroundColor", "" },
		{ "Classic.TopBarBackgroundColor", "Color(255, 255, 255)" },
		{ "Classic.TopBarForegroundColor", "Color(0, 0, 0)" },
		{ "Classic.TreeBackgroundColor", "" },
		{ "Classic.TreeSelectionBackgroundColor", "Color(0, 0, 255)" },
		{ "Classic.TreeUnfocusedSelectionBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.UseDoubleLineBorderForModal", "True" },
		{ "Classic.WindowBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.WindowForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.DropdownFocusedForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.DropdownFocusedBackgroundColor", "Color(0, 0, 255)" },
		{ "Classic.DropdownDisabledForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.DropdownDisabledBackgroundColor", "Color(128, 128, 128)" },
		{ "Classic.ListForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.ListFocusedForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.ListSelectedForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.ListSelectedBackgroundColor", "Color(0, 0, 128)" },
		{ "Classic.ListDisabledForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.ListDisabledBackgroundColor", "Color(128, 128, 128)" },
		{ "Classic.CheckboxForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.CheckboxFocusedForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.CheckboxDisabledForegroundColor", "Color(255, 255, 255)" },
		{ "Classic.CheckboxCheckmarkColor", "Color(255, 255, 255)" },
		{ "Classic.DatePickerDisabledBackgroundColor", "Color(128, 128, 128)" },
		{ "Classic.HtmlForegroundColor", "Color(255, 255, 255)" },
	};

	[Theory]
	[InlineData("ModernGray")]
	[InlineData("Classic")]
	public void BuiltInTheme_MembersUnchanged(string themeName)
	{
		ITheme theme = themeName == "ModernGray" ? new ModernGrayTheme() : new ClassicTheme();
		var mismatches = new List<string>();
		foreach (var p in typeof(ITheme).GetProperties(BindingFlags.Public | BindingFlags.Instance))
		{
			var actual = $"{p.GetValue(theme)}";
			var key = $"{themeName}.{p.Name}";
			if (!Golden.TryGetValue(key, out var expected))
				mismatches.Add($"{key}: NEW member not in golden set (value {actual})");
			else if (actual != expected)
				mismatches.Add($"{key}: expected {expected}, got {actual}");
		}
		Assert.True(mismatches.Count == 0, "built-in theme drifted from golden values:\n" + string.Join("\n", mismatches));
	}
}
