// -----------------------------------------------------------------------
// ConsoleEx - A simple console window system for .NET Core
//
// Author: Nikolaos Protopapas
// Email: nikolaos.protopapas@gmail.com
// License: MIT
// -----------------------------------------------------------------------

#pragma warning disable CS1591

namespace SharpConsoleUI
{
	/// <summary>
	/// Maps color names to Color values. Used by the markup parser and
	/// <see cref="Color.TryFromName"/> for name-based color resolution.
	/// Names are case-insensitive and underscore/space-tolerant.
	/// </summary>
	internal static class ColorTable
	{
		private static readonly Dictionary<string, Color> NameToColor =
			new(StringComparer.OrdinalIgnoreCase)
		{
			// Basic 16
			["default"] = Color.Default,
			["black"] = Color.Black,
			["maroon"] = Color.Maroon,
			["green"] = Color.Green,
			["olive"] = Color.Olive,
			["navy"] = Color.Navy,
			["purple"] = Color.Purple,
			["teal"] = Color.Teal,
			["silver"] = Color.Silver,
			["grey"] = Color.Grey,
			["gray"] = Color.Grey,
			["red"] = Color.Red,
			["lime"] = Color.Lime,
			["yellow"] = Color.Yellow,
			["blue"] = Color.Blue,
			["fuchsia"] = Color.Fuchsia,
			["magenta"] = Color.Fuchsia,
			["aqua"] = Color.Aqua,
			["cyan"] = Color.Aqua,
			["white"] = Color.White,

			// Aliases — xterm-256 values for Spectre markup compatibility
			["darkred"] = new Color(95, 0, 0),        // xterm #52
			["darkgreen"] = new Color(0, 95, 0),      // xterm #22
			["darkyellow"] = Color.DarkYellow,         // no xterm equivalent, keep basic-16
			["darkblue"] = new Color(0, 0, 135),       // xterm #18
			["darkmagenta"] = new Color(135, 0, 135),  // xterm #90
			["darkcyan"] = new Color(0, 175, 135),     // xterm #36

			// Extended palette
			["orange1"] = Color.Orange1,
			["darkorange"] = Color.DarkOrange,
			["indianred"] = Color.IndianRed,
			["hotpink"] = Color.HotPink,
			["deeppink1"] = Color.DeepPink1,
			["mediumorchid"] = Color.MediumOrchid,
			["darkviolet"] = Color.DarkViolet,
			["blueviolet"] = Color.BlueViolet,
			["royalblue1"] = Color.RoyalBlue1,
			["cornflowerblue"] = Color.CornflowerBlue,
			["dodgerblue1"] = Color.DodgerBlue1,
			["deepskyblue1"] = Color.DeepSkyBlue1,
			["steelblue"] = Color.SteelBlue,
			["cadetblue"] = Color.CadetBlue,
			["mediumturquoise"] = Color.MediumTurquoise,
			["darkturquoise"] = Color.DarkTurquoise,
			["lightseagreen"] = Color.LightSeaGreen,
			["mediumspringgreen"] = Color.MediumSpringGreen,
			["springgreen1"] = Color.SpringGreen1,
			["chartreuse1"] = Color.Chartreuse1,
			["greenyellow"] = Color.GreenYellow,
			["darkolivegreen1"] = Color.DarkOliveGreen1,
			["palegreen1"] = Color.PaleGreen1,
			["darkseagreen"] = Color.DarkSeaGreen,
			["mediumseagreen"] = Color.MediumSeaGreen,
			["lightgreen"] = Color.LightGreen,
			["khaki1"] = Color.Khaki1,
			["darkkhaki"] = Color.DarkKhaki,
			["darkgoldenrod"] = Color.DarkGoldenrod,
			["wheat1"] = Color.Wheat1,
			["navajowhite1"] = Color.NavajoWhite1,
			["mistyrose1"] = Color.MistyRose1,
			["lightcoral"] = Color.LightCoral,
			["salmon1"] = Color.Salmon1,
			["lightsalmon1"] = Color.LightSalmon1,
			["lightpink1"] = Color.LightPink1,
			["pink1"] = Color.Pink1,
			["plum1"] = Color.Plum1,
			["orchid"] = Color.Orchid,
			["violet"] = Color.Violet,
			["thistle1"] = Color.Thistle1,
			["sandybrown"] = Color.SandyBrown,
			["tan"] = Color.Tan,
			["rosybrown"] = Color.RosyBrown,
			["palevioletred"] = Color.PaleVioletRed,
			["mediumvioletred"] = Color.MediumVioletRed,
			["mediumpurple"] = Color.MediumPurple,
			["mediumslateblue"] = Color.MediumSlateBlue,
			["slateblue1"] = Color.SlateBlue1,
			["lightsteelblue"] = Color.LightSteelBlue,
			["lightblue"] = Color.LightBlue,
			["lightcyan1"] = Color.LightCyan1,
			["paleturquoise1"] = Color.PaleTurquoise1,
			["lightskyblue1"] = Color.LightSkyBlue1,
			["skyblue1"] = Color.SkyBlue1,
			["lightslategrey"] = Color.LightSlateGrey,
			["lightslategray"] = Color.LightSlateGrey,
			["honeydew2"] = Color.Honeydew2,
			["lightgoldenrodyellow"] = Color.LightGoldenrodYellow,
			["lightyellow1"] = Color.LightYellow1,
			["darkslategray1"] = Color.DarkSlateGray1,
			["darkslategray3"] = Color.DarkSlateGray3,
			["cyan1"] = Color.Cyan1,
			["orange3"] = Color.Orange3,
			["magenta1"] = Color.Magenta1,
			["dodgerblue2"] = Color.DodgerBlue2,
			["springgreen2"] = Color.SpringGreen2,
			["chartreuse2"] = Color.Chartreuse2,
			["gold1"] = Color.Gold1,
			["gold3"] = Color.Gold3,
			["coral"] = Color.Coral,

			// xterm-256 palette — full Spectre.Console compatibility
			["navyblue"] = Color.NavyBlue,
			["blue3"] = Color.Blue3,
			["blue31"] = Color.Blue3_1,
			["blue1"] = Color.Blue1,
			["deepskyblue4"] = Color.DeepSkyBlue4,
			["deepskyblue41"] = Color.DeepSkyBlue4_1,
			["deepskyblue42"] = Color.DeepSkyBlue4_2,
			["dodgerblue3"] = Color.DodgerBlue3,
			["green4"] = Color.Green4,
			["springgreen4"] = Color.SpringGreen4,
			["turquoise4"] = Color.Turquoise4,
			["deepskyblue3"] = Color.DeepSkyBlue3,
			["deepskyblue31"] = Color.DeepSkyBlue3_1,
			["green3"] = Color.Green3,
			["springgreen3"] = Color.SpringGreen3,
			["deepskyblue2"] = Color.DeepSkyBlue2,
			["green31"] = Color.Green3_1,
			["springgreen31"] = Color.SpringGreen3_1,
			["cyan3"] = Color.Cyan3,
			["turquoise2"] = Color.Turquoise2,
			["green1"] = Color.Green1,
			["springgreen21"] = Color.SpringGreen2_1,
			["cyan2"] = Color.Cyan2,
			["deeppink4"] = Color.DeepPink4,
			["purple4"] = Color.Purple4,
			["purple41"] = Color.Purple4_1,
			["purple3"] = Color.Purple3,
			["orange4"] = Color.Orange4,
			["mediumpurple4"] = Color.MediumPurple4,
			["slateblue3"] = Color.SlateBlue3,
			["slateblue31"] = Color.SlateBlue3_1,
			["chartreuse4"] = Color.Chartreuse4,
			["darkseagreen4"] = Color.DarkSeaGreen4,
			["paleturquoise4"] = Color.PaleTurquoise4,
			["steelblue3"] = Color.SteelBlue3,
			["chartreuse3"] = Color.Chartreuse3,
			["darkseagreen41"] = Color.DarkSeaGreen4_1,
			["cadetblue1"] = Color.CadetBlue_1,
			["skyblue3"] = Color.SkyBlue3,
			["steelblue1"] = Color.SteelBlue1,
			["chartreuse31"] = Color.Chartreuse3_1,
			["palegreen3"] = Color.PaleGreen3,
			["seagreen3"] = Color.SeaGreen3,
			["aquamarine3"] = Color.Aquamarine3,
			["steelblue11"] = Color.SteelBlue1_1,
			["seagreen2"] = Color.SeaGreen2,
			["seagreen1"] = Color.SeaGreen1,
			["seagreen11"] = Color.SeaGreen1_1,
			["aquamarine1"] = Color.Aquamarine1,
			["darkslategray2"] = Color.DarkSlateGray2,
			["darkred1"] = Color.DarkRed_1,
			["deeppink41"] = Color.DeepPink4_1,
			["darkmagenta1"] = Color.DarkMagenta_1,
			["darkviolet1"] = Color.DarkViolet_1,
			["purple1"] = Color.Purple_1,
			["orange41"] = Color.Orange4_1,
			["lightpink4"] = Color.LightPink4,
			["plum4"] = Color.Plum4,
			["mediumpurple3"] = Color.MediumPurple3,
			["mediumpurple31"] = Color.MediumPurple3_1,
			["yellow4"] = Color.Yellow4,
			["wheat4"] = Color.Wheat4,
			["lightslateblue"] = Color.LightSlateBlue,
			["yellow41"] = Color.Yellow4_1,
			["darkolivegreen3"] = Color.DarkOliveGreen3,
			["lightskyblue3"] = Color.LightSkyBlue3,
			["lightskyblue31"] = Color.LightSkyBlue3_1,
			["skyblue2"] = Color.SkyBlue2,
			["chartreuse21"] = Color.Chartreuse2_1,
			["darkolivegreen31"] = Color.DarkOliveGreen3_1,
			["palegreen31"] = Color.PaleGreen3_1,
			["darkseagreen3"] = Color.DarkSeaGreen3,
			["lightgreen1"] = Color.LightGreen_1,
			["aquamarine11"] = Color.Aquamarine1_1,
			["red3"] = Color.Red3,
			["deeppink42"] = Color.DeepPink4_2,
			["magenta3"] = Color.Magenta3,
			["purple2"] = Color.Purple_2,
			["darkorange3"] = Color.DarkOrange3,
			["hotpink3"] = Color.HotPink3,
			["mediumorchid3"] = Color.MediumOrchid3,
			["mediumpurple2"] = Color.MediumPurple2,
			["lightsalmon3"] = Color.LightSalmon3,
			["mediumpurple21"] = Color.MediumPurple2_1,
			["mediumpurple1"] = Color.MediumPurple1,
			["gold31"] = Color.Gold3_1,
			["navajowhite3"] = Color.NavajoWhite3,
			["lightsteelblue3"] = Color.LightSteelBlue3,
			["yellow3"] = Color.Yellow3,
			["darkolivegreen32"] = Color.DarkOliveGreen3_2,
			["darkseagreen31"] = Color.DarkSeaGreen3_1,
			["darkseagreen2"] = Color.DarkSeaGreen2,
			["lightcyan3"] = Color.LightCyan3,
			["darkolivegreen2"] = Color.DarkOliveGreen2,
			["palegreen11"] = Color.PaleGreen1_1,
			["darkseagreen21"] = Color.DarkSeaGreen2_1,
			["darkseagreen1"] = Color.DarkSeaGreen1,
			["red31"] = Color.Red3_1,
			["deeppink3"] = Color.DeepPink3,
			["deeppink31"] = Color.DeepPink3_1,
			["magenta31"] = Color.Magenta3_1,
			["magenta32"] = Color.Magenta3_2,
			["magenta2"] = Color.Magenta2,
			["darkorange31"] = Color.DarkOrange3_1,
			["hotpink31"] = Color.HotPink3_1,
			["hotpink2"] = Color.HotPink2,
			["mediumorchid1"] = Color.MediumOrchid1,
			["lightsalmon31"] = Color.LightSalmon3_1,
			["lightpink3"] = Color.LightPink3,
			["pink3"] = Color.Pink3,
			["plum3"] = Color.Plum3,
			["lightgoldenrod3"] = Color.LightGoldenrod3,
			["mistyrose3"] = Color.MistyRose3,
			["thistle3"] = Color.Thistle3,
			["plum2"] = Color.Plum2,
			["yellow31"] = Color.Yellow3_1,
			["khaki3"] = Color.Khaki3,
			["lightgoldenrod2"] = Color.LightGoldenrod2,
			["lightyellow3"] = Color.LightYellow3,
			["lightsteelblue1"] = Color.LightSteelBlue1,
			["yellow2"] = Color.Yellow2,
			["darkolivegreen11"] = Color.DarkOliveGreen1_1,
			["darkolivegreen12"] = Color.DarkOliveGreen1_2,
			["darkseagreen11"] = Color.DarkSeaGreen1_1,
			["red1"] = Color.Red1,
			["deeppink2"] = Color.DeepPink2,
			["deeppink11"] = Color.DeepPink1_1,
			["magenta21"] = Color.Magenta2_1,
			["orangered1"] = Color.OrangeRed1,
			["indianred1"] = Color.IndianRed1,
			["indianred11"] = Color.IndianRed1_1,
			["hotpink1"] = Color.HotPink_1,
			["mediumorchid11"] = Color.MediumOrchid1_1,
			["palevioletred1"] = Color.PaleVioletRed1,
			["orchid2"] = Color.Orchid2,
			["orchid1"] = Color.Orchid1,
			["yellow1"] = Color.Yellow1,
			["lightgoldenrod21"] = Color.LightGoldenrod2_1,
			["lightgoldenrod22"] = Color.LightGoldenrod2_2,
			["lightgoldenrod1"] = Color.LightGoldenrod1,
			["cornsilk1"] = Color.Cornsilk1,

			// Grey scale
			["grey0"] = Color.Grey0,
			["grey3"] = Color.Grey3,
			["grey7"] = Color.Grey7,
			["grey11"] = Color.Grey11,
			["grey15"] = Color.Grey15,
			["grey19"] = Color.Grey19,
			["grey23"] = Color.Grey23,
			["grey27"] = Color.Grey27,
			["grey30"] = Color.Grey30,
			["grey35"] = Color.Grey35,
			["grey37"] = Color.Grey37,
			["grey39"] = Color.Grey39,
			["grey42"] = Color.Grey42,
			["grey46"] = Color.Grey46,
			["grey50"] = Color.Grey50,
			["grey53"] = Color.Grey53,
			["grey54"] = Color.Grey54,
			["grey58"] = Color.Grey58,
			["grey62"] = Color.Grey62,
			["grey63"] = Color.Grey63,
			["grey66"] = Color.Grey66,
			["grey69"] = Color.Grey69,
			["grey70"] = Color.Grey70,
			["grey74"] = Color.Grey74,
			["grey78"] = Color.Grey78,
			["grey82"] = Color.Grey82,
			["grey84"] = Color.Grey84,
			["grey85"] = Color.Grey85,
			["grey89"] = Color.Grey89,
			["grey93"] = Color.Grey93,
			["grey100"] = Color.Grey100,
			// gray aliases
			["gray0"] = Color.Grey0,
			["gray3"] = Color.Grey3,
			["gray7"] = Color.Grey7,
			["gray11"] = Color.Grey11,
			["gray15"] = Color.Grey15,
			["gray19"] = Color.Grey19,
			["gray23"] = Color.Grey23,
			["gray27"] = Color.Grey27,
			["gray30"] = Color.Grey30,
			["gray35"] = Color.Grey35,
			["gray37"] = Color.Grey37,
			["gray39"] = Color.Grey39,
			["gray42"] = Color.Grey42,
			["gray46"] = Color.Grey46,
			["gray50"] = Color.Grey50,
			["gray53"] = Color.Grey53,
			["gray54"] = Color.Grey54,
			["gray58"] = Color.Grey58,
			["gray62"] = Color.Grey62,
			["gray63"] = Color.Grey63,
			["gray66"] = Color.Grey66,
			["gray69"] = Color.Grey69,
			["gray70"] = Color.Grey70,
			["gray74"] = Color.Grey74,
			["gray78"] = Color.Grey78,
			["gray82"] = Color.Grey82,
			["gray84"] = Color.Grey84,
			["gray85"] = Color.Grey85,
			["gray89"] = Color.Grey89,
			["gray93"] = Color.Grey93,
			["gray100"] = Color.Grey100,
		};

		/// <summary>
		/// Looks up a color by name. Normalizes underscores and spaces for tolerance.
		/// </summary>
		public static bool TryGetByName(string name, out Color color)
		{
			if (string.IsNullOrWhiteSpace(name))
			{
				color = default;
				return false;
			}

			// Normalize: strip underscores and spaces
			string normalized = name.Replace("_", "").Replace(" ", "");
			return NameToColor.TryGetValue(normalized, out color);
		}
	}
}
